---
title: "EDA"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
```

```{r load_data, cache=TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## Create a ggplot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()

```

#alternate way
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```


#Saving initial plots
```{r}
scatterplot = weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

#adding color
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color= name), alpha =.4)
```
Why does aes matter?
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color= name), alpha =.4) +
  geom_smooth(se = FALSE)
```
vs

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha =.4) +
  geom_smooth(se = FALSE)
```
facet!
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha =.4) +
  geom_smooth(se = FALSE) +
  facet_grid(~name)
```
This is fine, but not interesting...

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(size = 2, se = FALSE)
```
extra stuff
```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth(size = 2, se = FALSE)
```
2d density
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_bin2d()
```

